### ISSUE TITLE
flycheck-haskell-configure should be idempotent

### ISSUE THREAD

**Issue by gracjan** [flycheck/flycheck-haskell#19]
As per discussion in https://github.com/flycheck/flycheck-haskell/issues/14 flycheck-haskell-configure executed twice should have same result as execute once.

Right now it appends duplicate flags and that might cause issues when flag duplication is important.

**Comment by lunaryorn** [comment]
@gracjan I think we shouldn't bother for idempotency, IMHO.  It's probably easier, if we just override any previous values in this extension.

After all, the cabal file usually contains all relevant build settings, so why should anyone ever want to add additional settings just for Flycheck?

Your opinion?

**Comment by gracjan** [comment]
I see that we agree or at least I do not see how we disagree... do we?

*Overriding any previous values* is what I was after in this request.

Meanwhile current code has 'append' (not idempotent, not override):

    (setq-local flycheck-ghc-search-path
               (append .build-directories .source-directories
                       flycheck-ghc-search-path))

Better code (somewhat idempotent, but depends on extra settings, that usually gives surprising results):

    (setq-local flycheck-ghc-search-path
               (append .build-directories .source-directories
                       (default-value flycheck-ghc-search-path)))

Best code (depends only on contents of .cabal file and nothing else):

    (setq-local flycheck-ghc-search-path
               (append .build-directories .source-directories))
