### ISSUE TITLE
Error During Interactive Linking, GHCi Couldn't Find the Following Symbol

### ISSUE THREAD

**Issue by creichert** [flycheck/flycheck-haskell#21]
I receive the following error when I have `flycheck-haskell` enabled
and I attempt to use haskell-mode's `haskell-process-load-file`:

```
During interactive linking, GHCi couldn't find the following symbol:                
  Settings_staticDir_closure                                                        
This may be due to you not asking GHCi to load extra object files,                  
archives or DLLs needed by your current session.  Restart GHCi, specifying          
the missing library using the -L/path/to/object/dir and -lmissinglibname            
flags, or simply by naming the relevant files on the GHCi command line.             
Alternatively, this link failure might indicate a bug in GHCi.                      
If you suspect the latter, please send a bug report to:                             
  glasgow-haskell-bugs@haskell.org                                                  


Checker definition probably flawed.
```

This error is on a basic Yesod site and does not happen on other
(non-yesod) cabal projects. Yesod does use some CPP to conditionally
compile environments but I haven't quite figured out if that's related
to this issue (`staticDir` is a simple function `staticDir =
"static"`).

I'm not certain how to go about debugging this further. Let me know if
there is anything else I can do to help.

Thanks!

**Comment by razvan-panda** [comment]
@lunaryorn Do you happen to know if there is any way to avoid getting the message popup (appears on each save) without disabling flycheck (seems to still work despite the error)?

**Comment by lunaryorn** [comment]
@razvan-panda There's not.  I can add one if you make me an issue in the Flycheck issue tracker, but it'll take a long time, because it's not a high priority for me—it only affects flawed checkers after all—and I have many other things to do.
