### ISSUE TITLE
Checking c2hs files

### ISSUE THREAD

**Issue by ocramz** [flycheck/flycheck-haskell#32]
What should I modify to have Haskell linting/typechecking when editing c2hs .chs files (Haskell with C #includes and c2hs {# ... #} macros) ?
The major mode I use for .chs is M-x haskell-c-mode .

I already have FlyCheck working in haskell-mode and C mode sepately. 

Thank you in advance

**Comment by lunaryorn** [comment]
I took the liberty to edit your title.  There's no need to “tag” in the title—that's what Github labels are for.

As for the actual question: Flycheck does not support Haskell C Mode. I didn't even know that this mode existed until now—I seldom write c2hs code.

I don't know whether we can check these files in Flycheck.  As far as I know c2hs is just a preprocessor, which does not implement a complete Haskell compiler.  If that is true, I don't think that we have a chance to check these files.

Flycheck would need to run c2hs to obtain a Haskell source, then run that through GHC, parse these errors, and eventually “map” the parsed errors back to the c2hs source—which is quite hard, since Flycheck cannot easily figure out how much text was inserted by c2hs.

I'm open to better ideas, or even pull requests, but as things stand now you cannot use Flycheck on c2hs files.

**Comment by lunaryorn** [comment]
Probably @purcell can contribute his ideas.

**Comment by ocramz** [comment]
Thank you for the feedback; c2hs does output line annotations in its output, in form of pragmas:
{-# LINE n "Main.chs" #-} , but I don't know how these could be useful..

**Comment by purcell** [comment]
One option would probably be to write a `c2hslint` tool which could contain the logic @lunaryorn describes, and produce output convenient for `flycheck`.

**Comment by lunaryorn** [comment]
@ocramz Do these pragmas actually change the line numbers in the GHC output?  In this case much of what I've said above would become redundant, and all we'd be left to do was to pipe the c2hs output to GHC.

Flycheck doesn't provide an infrastructure for this kind of preprocessing—if it becomes a bigger issue, we could add one of course—but it'd be quite easy to write a simple script for this purpose.   A small Python script would suffice…

**Comment by ocramz** [comment]
the {-# LINE #-} pragmas just refer back to the position of the originating macro in the .chs file.
E.g. 

    accessStruct1 :: (TestPtr) -> IO ((Int))
    accessStruct1 a1 =
      let {a1' = id a1} in 
      accessStruct1'_ a1' >>= \res ->
      let {res' = fromIntegral res} in
      return (res')

     {-# LINE 12 "PointersTest2.chs" #-}

is an expansion of the following macro, contained on line 12 of the .chs : 

    {# fun access_struct1 as accessStruct1 {`TestPtr'} -> `Int'#}

Or have I misunderstood the question?

**Comment by lunaryorn** [comment]
@ocramz I think so.  I *know* that the line pragmas reference the source position of the unexpanded file, i.e. before c2hs processing.  I wanted to know whether these pragmas actually affect GHC's output.

In other words, if there's an error, does GHC output line numbers from the expanded .hs file, or does it somehow evaluate the line pragmas and output line numbers from the unexpanded c2hs file?

**Comment by ocramz** [comment]
If there's a c2hs error, no .hs gets generated. I should talk to c2hs's current maintainer, Ian Ross, @iross, regarding intermediate cases or ways to make the c2hs output more verbose (the wiki does not mention this and the internal help is quite terse).

**Comment by ian-ross** [comment]
As Marco says, if there's an error in the C2HS file, no Haskell file gets generated.  If there's an error in the generated Haskell file, the GHC error messages refer to lines in the original .chs file (the second possibility @lunaryorn's question above).

This ought to be manageable with a simple wrapper around C2HS+GHC: if C2HS errors, just handle the C2HS error messages; if C2HS succeeds, run GHC on the resulting Haskell file and deal with any GHC errors (which refer back to the original .chs file).

**Comment by lunaryorn** [comment]
@ocramz We're still talking past each other.  I was talking about GHC errors, i.e. what line numbers are used if there's GHC error in the generated file.

@ian-ross Thanks for joining this discussion.  If the GHC error messages refer to lines in the original c2hs file, it's indeed quite easy to write a wrapper around it.  I'll try to write it, but I'm short of time, and can't promise anything soon.

If anyone else wants to take a shot, I'd welcome a pull request.

Thank you all for this discussion!

**Comment by lunaryorn** [comment]
Closing as wontfix.  I don't need this myself, and I don't have time for it.  Pull requests welcome :)
