### ISSUE TITLE
FlyCheck unable to find sandboxed packages

### ISSUE THREAD

**Issue by geraldus** [flycheck/flycheck-haskell#33]
Currently I'm using shared sandbox created by **Stackage CLI**<sup>[1]</sup>, but I had same problem with normal sandbox. **FlyCheck** reports me a lot of `haskell-ghc` checker `"Could not find module"` errors when checking sandboxed project (output of `C-c ! C-c haskell-ghc RET`):

> -*- mode: compilation; default-directory: "~/Haskell/SandBox/" -*-
> Compilation started at Tue May 26 17:52:21
> 
> ghc -Wall -fno-code -i/Users/arthurfayzrakhmanov/Haskell/SandBox/ -x hs /Users/arthurfayzrakhmanov/Haskell/SandBox/Foundation.hs
> 
> Handler/Form/Import.hs:13:18:
>     Could not find module ‘Text.Shakespeare.I18N’
>     Use -v to see a list of the files searched for.
> 
> Handler/Form/Import.hs:14:18:
>     Could not find module ‘Yesod.Core’
>     Use -v to see a list of the files searched for.
> 
> Handler/Form/Import.hs:15:18:
>     Could not find module ‘Yesod.Form.Fields’
>     Use -v to see a list of the files searched for.
> … and so on 

And `cabal list --installed` from project root makes sure that modules are actually installed:

```
$ cabal list --installed

…

* shakespeare
    Synopsis: A toolkit for making compile-time interpolated templates
    Default available version: 2.0.5
    Installed versions: 2.0.5
    Homepage: http://www.yesodweb.com/book/shakespearean-templates
    License:  MIT 
…

* yesod-core
    Synopsis: Creation of type-safe, RESTful web applications.
    Default available version: 1.4.9.1
    Installed versions: 1.4.9.1
    Homepage: http://www.yesodweb.com/
    License:  MIT

* yesod-form
    Synopsis: Form handling support for Yesod Web Framework
    Default available version: 1.4.4.1
    Installed versions: 1.4.4.1
    Homepage: http://www.yesodweb.com/
    License:  MIT

…
```

I guess this is because of checker use `ghc -Wall -fno-code -i<path>` command; should it use `cabal` in case of sandboxed projects?

[1]:https://github.com/fpco/stackage-cli

**Comment by lunaryorn** [comment]
Please show the output of `C-c ! v` and `C-c ! C-c haskell-ghc`.  Does it work after `M-x normal-mode`?

**Comment by lunaryorn** [comment]
Besides, it's Flycheck, not FlyCheck, and there's no reason to emphasize it…

**Comment by lunaryorn** [comment]
And, additionally, please show me your Flycheck Haskell setup from your init file.

**Comment by geraldus** [comment]
Please excuse me, I've updated `flycheck-haskell` and now the issue is not relevant!
BTW, `C-c ! v` showed me green statuses for each checker and I don't know where did I get this capital C from! (:

**Comment by lunaryorn** [comment]
@geraldus Never mind :) I'm unsure how a Flycheck update could have solved this, unless you used a very old version, but I'm happy that it works for you now :)
