### ISSUE TITLE
flycheck-haskell does not work with haskell-mode installed from source

### ISSUE THREAD

**Issue by geraldus** [flycheck/flycheck-haskell#34]
I'm hacking `haskell-mode` from time to time and decided to install it from git sources rather than from **MELPA** PA. Now `flycheck-haskell` fails to start with following output:

```
Warning (emacs): Unable to activate package `flycheck-haskell'.
Required package `haskell-mode-13.7' is unavailable
```

I guess this is because of this<sup>[1]</sup>. But likely it defines minimal required version, so I have no idea what's wrong. Current `haskell-mode` version is `13.12`.

[1]:https://github.com/flycheck/flycheck-haskell/blob/7d9466c34f50ca5bf1815dc007e0b3f682fd8b03/flycheck-haskell.el#L11

**Comment by gracjan** [comment]
Interesting. How can we advertise from source that `haskell-mode` is available and working?

**Comment by geraldus** [comment]
em, `fboundp`?

**Comment by gracjan** [comment]
Seems like manual calling of `package-load-descriptor` with single argument that is the directory where `haskell-mode` is gitcloned should do the trick.

**Comment by lunaryorn** [comment]
You can't.  If you install a package through the package manager you must install all its dependencies through the package manager as well.  There's no reliable way around this.

In other words, you must install Haskell Mode like you install flycheck-haskell.

Closing since this is not an issue in this library, but a configuration error.

**Comment by gracjan** [comment]
@lunaryorn: yes, you should close this isse.

Still we need to find a way as it is impossible to hack on `haskell-mode` otherwise and we really need to do this.

**Comment by geraldus** [comment]
@lunaryorn feel free to close! (: so, in my case I need to install `flycheck-haskell` (and `flycheck` itself?) from source to resolve this?

**Comment by lunaryorn** [comment]
Well, you can install this library from GitHub as well.  I don't support that but as Emacs developers you should be able to cope with any issues that might occur 😀

**Comment by lunaryorn** [comment]
Or you install Haskell Mode from MELPA as well, and then just reload it when you want to makes changes to it.  That's what Emacs has `eval-buffer` and friends for, and that's what I do with Flycheck.

**Comment by geraldus** [comment]
:smile: well, I'm using `eval-buffer` constantly. The issue is `haskell-mode` tests, it picks up precompiled haskell-mode sources when doing tests, so often tests fails. But I have easier solution: just remove all `*.elc` files from haskell-mode. Anyway, thank you for clarifications, I'll stick with MELPA installation.

**Comment by lunaryorn** [comment]
@geraldus I'm not sure what you mean, but then I don't know how the test suite of Haskell Mode works either.  But there should be a script or Makefile target or anything of that sort to run all Haskell Mode tests from a Git checkout, using the Git version.  If there isn't, that's probably something that you can contribute to Haskell Mode :)

**Comment by geraldus** [comment]
@lunaryorn for example I've removed third arg from `some-funciton` and updated all code where it used. Now if I'll run tests (`make check` in this case) it will fail with error message alike `"function `some-function' takes exactly 3 args, but was given only 2"`. The workaround is to remove `*.elc` files from `haskell-mode` folder (from where `make` command ran). Excuse me for nonce noise (:

**Comment by lunaryorn** [comment]
@geraldus I'd argue that this is an issue in the makefile of Haskell Mode.  `make check` should depend on the compilation target if it uses byte code files.

**Comment by gracjan** [comment]
Noted an issue in our github issue tracker.
