### ISSUE TITLE
flycheck-haskell fails when sandbox isn't present

### ISSUE THREAD

**Issue by mdorman** [flycheck/flycheck-haskell#36]
At least, I don't use sandboxes, and the reference to package-db in the error message:

    Error while checking syntax automatically: (error "Value (nil) of flycheck-ghc-package-databases for option \"-package-db\" is not a list of strings") [10 times]

(which seems only used with sandboxes) would seem to point the finger at the sandbox support.

I created #35 to resolve this.

**Comment by lunaryorn** [comment]
Isn't this the same as #35?

**Comment by mdorman** [comment]
Yes, entirely.  Lately I've found some maintainers don't seem to look at PRs unless there are issues associated with them, so I've gotten into the habit of doing both.  Sorry for the noise.

**Comment by lunaryorn** [comment]
@mdorman Closing as duplicate then.
