### ISSUE TITLE
Suspicious state from syntax checker javascript-eslint

### ISSUE THREAD

**Issue by blakehaswell** [flycheck/flycheck-haskell#38]
I’ve got flycheck configured as per [this blog post](http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html), but I’m getting the following error code which I’m unable to solve.

    Suspicious state from syntax checker javascript-eslint: Checker javascript-eslint returned non-zero exit code 127, but no errors from output: env: node: No such file or directory

    Checker definition probably flawed.

If I run eslint manually I don’t get any such errors:

    $ eslint /my-file.jsx

    /my-file.jsx
      2:7  error  PurchaseDetail is defined but never used    no-unused-vars
      3:7  error  PurchaseForm is defined but never used      no-unused-vars
      4:7  error  DayBudgetDetails is defined but never used  no-unused-vars

    ✖ 3 problems (3 errors, 0 warnings)

Any ideas?

**Comment by lunaryorn** [comment]
@blakehaswell Your Emacs seems to have the wrong `$PATH`, which you might be able to solve with `exec-path-from-shell`, presuming that you're on OS X, but how's that all related to Haskell, and why do you ask me and not the author of the blog post whose instructions you followed?

Closing as invalid.

**Comment by blakehaswell** [comment]
Ugh, apologies, I don’t even know how I ended up in this project – clicked the wrong tab I guess. Thanks for pointing me in the right direction regardless.
