### ISSUE TITLE
Cabal defined CPP macros dont work.

### ISSUE THREAD

**Issue by s9gf4ult** [flycheck/flycheck-haskell#39]
Code like this: 

```haskell
#if MIN_VERSION_monad_control(1, 0, 0)
```

is highlighted as wrong with such error message:

```
error: missing binary operator before token "("
#if MIN_VERSION_monad_control(1, 0, 0)
```

It looks like `flycheck-haskell` do not take cabal defined macros into account.

PS. Why dont just use `cabal build` to build modules, or just get all parameters which `cabal` gives to `ghc` using e.g. http://hackage.haskell.org/package/cabal-cargs ?

**Comment by lunaryorn** [comment]
> It looks like flycheck-haskell do not take cabal defined macros into account.

It doesn't.  You can easily add the necessary macros to the corresponding options, though.

> PS. Why dont just use cabal build to build modules, or just get all parameters which cabal gives to ghc using e.g. http://hackage.haskell.org/package/cabal-cargs ?

If you ask me this way, I'd say that **I** didn't yet need this myself, and none else–including you—has bothered to make a pull request…

**Comment by ntc2** [comment]
@lunaryorn: could you explain how to "add the necessary macros to the corresponding options"? I'm getting a similar error from `#if !MIN_VERSION_base(4,8.0)` guards.

**Comment by lunaryorn** [comment]
@ntc2 There's `flycheck-ghc-args` which is simple a list of additional flags for GHC in Flycheck.  You can add `-cpp` and `-DMIN_VERSION_base(4, 8, 0)` to it to define the macro for Flycheck syntax checking/

**Comment by ntc2** [comment]
@lunaryorn: thanks for your help! Adding `-cpp` and `-DMIN_VERSION_base(4, 8, 0)` to `flycheck-ghc-args` did not work for me, but I was able to find other settings that do work.

Following a blog (http://www.christopherbiscardi.com/tag/min_version_base/) I found that adding
```
"-I<absolute path in Cabal sandbox to>/build/autogen" "-optP-include" "-optPcabal_macros.h"
```
to `flycheck-ghc-args` works,  because `cabal_macros.h` is where the `MIN_VERSION` macros are defined.

Then, following @s9gf4ult 's suggestion, I found that installing `cabal-cargs` and doing `(setq flycheck-ghc-args (split-string (shell-command-to-string "cabal-cargs")))` achieves this in a more general way (although might be broken if any paths had spaces in them; my paths do not).

The above fixes make the FlyCheck `haskell-ghc` checker succeed, but `haskell-hlint` still fails with
```
Suspicious state from syntax checker haskell-hlint: Checker haskell-hlint returned non-zero exit code 1, but no errors from output: hlint: Cannot expand #if directive in file /home/conathan/cfar/reopt.git/src/Reopt/Concrete/flycheck_Semantics.hs  at line 39 col 1:
    MIN_VERSION_base(a,b,c) is not a defined macro

Checker definition probably flawed.
```
(No idea what's going on with the `flycheck_` on the path in the error message.)

**Comment by lunaryorn** [comment]
@ntc2 The prefix comes from the temporary file that Flycheck creates to check modified buffers.

You'd need to define the macro for hlint as well, but I don't know how to do that.  Presumably there's an hlint option for that, but it don't think it's wrapped in Flycheck.

Please open a new issue on Flycheck's main issue tracker for the hlint problem.  Thanks.

**Comment by mrkkrp** [comment]
If anyone is having trouble with this, easiest solution, IMHO is this:

```emacs-lisp
(add-to-list
 'flycheck-ghc-args
 '("-cpp"
   "-DMIN_VERSION_base(x,y,z)"))
```

This worked for me, no need to install anything with Cabal. Not sure there are any adverse effects.

**Comment by ntc2** [comment]
@mrkkrp: in general any package `<pkg>` can have a `MIN_VERSION_<pkg>` macro -- I think Cabal generates one for each dependency in the `.cabal` -- but in practice not many of them get used. So, no adverse effects, but that is not a general solution.

**Comment by mrkkrp** [comment]
@ntc2, Yeah, true, although I'm sure in 90% of cases it's `base`. What about progress with that hlint issue? Should I try to add option for hlint parameters? Unless someone already doing this, I think I will open a PR, because this would fix the problem for me completely.

**Comment by ntc2** [comment]
@mrkkrp: it doesn't look like anything is happening on the `hlint` issue. You're right that `MIN_VERSION_base` is the common case, although grepping through projects I've worked on recently I also see `MIN_VERSION_` macros for `template_haskell`, `time`, and `directory` in use. Of course, it's not hard to add three more `-D` args to `flycheck-ghc-args` :)

**Comment by lunaryorn** [comment]
I [clearly said right away](https://github.com/flycheck/flycheck/issues/713#issuecomment-127970675) that I won't add that myself and will leave that to someone else's pull request.  I haven't got any so far, so I'm definitely not going to take any blame for that issue still being open.

**Comment by mrkkrp** [comment]
@lunaryorn, I personally don't blame you at all, I just asked if anyone is already doing that.

**Comment by ntc2** [comment]
@lunaryorn: sorry, I was not intending to blame you or anyone else. I was just responding to @mrkkrp's question about whether any progress has been made on the issue. I really appreciate all your hard work on `flycheck`; I have contributed nothing.

**Comment by mrkkrp** [comment]
@ntc2, OK, my PR introducing `flycheck-hlint-args` has been merged, so now I use this:

```emacs-lisp
(defun mk-haskell-set-min-versions (lib-list)
  "Help Flycheck handle Cabal MIN_VERSION_ definitions.

LIB-LIST should of the following form:

  (LIB-NAME V0 V1 V2)

Where LIB-NAME is a string, name of library and V0, V1, V2 are
version components."
  (add-to-list 'flycheck-ghc-args   "-cpp")
  (add-to-list 'flycheck-hlint-args "-XCPP")
  (dolist (item lib-list)
    (cl-destructuring-bind (lib a b c) item
      (add-to-list
       'flycheck-ghc-args
       (format "-DMIN_VERSION_%s(a,b,c)=(a<=%d&&b<=%d&&c<=%d)"
               lib a b c))
      (add-to-list
       'flycheck-hlint-args
       (format "--cpp-define=MIN_VERSION_%s(a,b,c)=(a<=%d&&b<=%d&&c<=%d)"
               lib a b c)))))

(mk-haskell-set-min-versions
 '(("base" 4 8 0)))
```

No, I don't like it either, but everything is working fine at last.
