### ISSUE TITLE
Can we have support for stack?

### ISSUE THREAD

**Issue by alcidesv** [flycheck/flycheck-haskell#41]
Haskell stack is kind of nice for big projects. It would be cool if flycheck-haskell would support it. 

I have hacked some code for that, but I'm out of my dept when it comes to elisp. Anyway, here is the code:

https://github.com/alcidesv/flycheck-haskell

Suggestions are appreciated.

**Comment by lunaryorn** [comment]
See https://github.com/flycheck/flycheck/pull/711
