### ISSUE TITLE
cabal sandbox packages not included in GHC command

### ISSUE THREAD

**Issue by atilaneves** [flycheck/flycheck-haskell#46]
Right now on Arch Linux, flycheck-haskell is not setting the correct variables for ghc to find the packages. For instance, on a file with `import Data.List.Split (splitOn)` flycheck fails with `could not find module Data.List.Split`, just as if flycheck-haskell was not installed / configured. This used to work.

I looked into all the variables set by this package and compared to the actual ghc command used by `cabal build` and found that it's not using `-i` flags to tell ghc where to find the packages, but `-package-id` set to `split-0.2.2-204e96694e892969ddc6c0f253af01bd`. Once I manually set `flycheck-ghc-args` to `-package-id split-0.2.2-204e96694e892969ddc6c0f253af01bd` it correctly found the package.

The fix would be to do what `cabal build` does and set `flycheck-ghc-args` to a collection of `package-id` followed by each package dependency.

**Comment by lunaryorn** [comment]
@atilaneves I don't think that you need pass these flags to GHC.  It should be able to find packages on its own in the given packages.

Do you have a Cabal sandbox for the project?

**Comment by atilaneves** [comment]
I just tried reproducing on a different machine and... couldn't. They're both running Arch Linux as well, so I don't know what's different between the two of them. I even deleted my `.emacs.d` and recloned it but the older machine still has the problem, and it's solved by setting `flycheck-ghc-flags` manually. Same OS, same Emacs configuration, same repository, different behaviour.

What else should I look at?

**Comment by lunaryorn** [comment]
@atilaneves Again, do you use a sandbox for the project?  If so, does Flycheck Haskell find it?

**Comment by atilaneves** [comment]
I use a sandbox and AFAICT flycheck-haskell finds it. I created a toy one [here](https://github.com/atilaneves/cabal_sandbox_test) hoping to demonstrate the problem but instead I demonstrated it works fine on one computer but not on the other.

**Comment by lunaryorn** [comment]
@atilaneves I must be an issue with your system then.   I'm closing this issue, but please feel free to write further comments if you need help.
