### ISSUE TITLE
Flycheck doesn't work with Stack project

### ISSUE THREAD

**Issue by mrkkrp** [flycheck/flycheck-haskell#47]
I'm editing files of Stack:

https://github.com/commercialhaskell/stack

and this is quite big project, of course. I've noticed that Flycheck works fine for modules in `src/Stack/Types/` and doesn't work at all for `src/Stack/Fetch.hs` for example. Maybe this is because the latter depends on more modules? I don't know. Is there any limitations on Flycheck usability? Should it work with projects of this size?

**Comment by lunaryorn** [comment]
I do not know either.   I'll need more information that “doesn't work at all” to say anything reasonable.

**Comment by mrkkrp** [comment]
Understandable, I'll do additional investigation when I have time.

**Comment by mrkkrp** [comment]
Hmm, take file `src/Stack/Fetch.hs`. If I edit something in the beginning of document, Flycheck works. About line 66, Flycheck stops to response to my edits. Message buffer does not contain anything of interest. How do I debug it? Can you clone the repo and try yourself?

**Comment by lunaryorn** [comment]
@mrkkrp Uhm, a first step would be to see what checker Flycheck actually uses, e.g. by `M-x flycheck-verify-setup`.  Then try to run the checker with `M-x flycheck-compile`.  It's probably just taking a long time to check, since it'll build all dependent modules on the first check, too.

You can also wait for me to try, but that'll take long time.  I'm not using Haskell currently—Rust and Elixir have recently caught my attention—and this issue has a low priority for me personally.  It'll likely take a long time before I find the time and motivation to actually sit down and try it.  Sorry.

**Comment by mrkkrp** [comment]
@lunaryorn, It's all right, I'll try to find out what's going on myself.

**Comment by mrkkrp** [comment]
First of all, `flycheck-verify-setup` told me that after recent chaning of `PATH` variable `hlint` is no longer on my `PATH`. Good catch, but this cannot be cause on this problem.

`flycheck-compile` however showed this (alignment added):

```
stack ghc -- -Wall -no-link -outputdir
/tmp/flycheck-haskell-ghc-cache60927MI
-XHaskell2010
-i/home/mark/projects/programs/haskell/stack/dist/build
-i/home/mark/projects/programs/haskell/stack/dist/build/autogen
-i/home/mark/projects/programs/haskell/stack/dist/build/stack/stack-tmp
-i/home/mark/projects/programs/haskell/stack/src/
-i/home/mark/projects/programs/haskell/stack/src/main
-i/home/mark/projects/programs/haskell/stack/src/test
-i/home/mark/projects/programs/haskell/stack/src/
-Wall -DMIN_VERSION_base\(a\,b\,c\)\=\(a\<\=4\&\&b\<\=8\&\&c\<\=0\)
-cpp -x hs /home/mark/projects/programs/haskell/stack/src/Stack/Fetch.hs

/home/mark/projects/programs/haskell/stack/src/Network/HTTP/Download/Verified.hs:33:8:
    Ambiguous module name ‘Crypto.Hash’:
      it was found in multiple packages:
      cryptonite-0.6@crypt_1A87AV0e5C8BaBsLLV3mNF cryptohash-0.11.6@crypt_5epyAhdyCoGIBkp2icUC24

/home/mark/projects/programs/haskell/stack/src/Stack/Types/Config.hs:54:18:
    Could not find module ‘Paths_stack’
    it is a hidden module in the package ‘stack-0.1.7.0@stack_HkplmoJrUgzABAqObuOfsF’
    Use -v to see a list of the files searched for.

Compilation exited abnormally with code 1 at Fri Nov  6 16:39:01
```

I've opened an issue on Stack, see commercialhaskell/stack#1300.

**Comment by mrkkrp** [comment]
Here is what maintainer of Stack says:

> This is an issue with flycheck — it isn't passing the `-package` flags which restrict the set of packages to just the ones that the project depends on.

> Also, it looks like it's using cabal's dist directory, so it won't find the `Paths_stack.hs` file in autogen.

In case you don't intend to work on this, should I try to prepare a pull request fixing these things? Any advice where to look and what to change would be helpful too.

**Comment by lunaryorn** [comment]
I'd have thought that `stack ghc` did that for us, but apparently not.  

I think you'd need to extend this project to add `-package` flags for all dependencies to `flycheck-ghc-args`.  We probably already extract the dependencies from Cabal files, but I think we currently ignore them.

And you'd have to extend this project add whatever directory contains `Paths_stack.hs` to the GHC search path.

**Comment by lunaryorn** [comment]
@mrkkrp Oh, sorry, I totally forgot this pull request :cry:  I'll take a look soon, and hope to merge it by this weekend!

**Comment by lunaryorn** [comment]
@mrkkrp I've cherry-picked the corresponding part of #48; the current MELPA should fix this issue.
