### ISSUE TITLE
Support for / use of extensions in .cabal

### ISSUE THREAD

**Issue by t-ander** [flycheck/flycheck-haskell#55]
Hello,

It seems that flycheck is reporting errors without respect to the extensions listed in the .cabal file. For instance I found that `mdo`-notation was flagged as a parse error regardless of the presence of `RecursiveDo` in `default-extensions`. (Adding a `{-# language RecursiveDo #-}` pragma to the file makes the error go away for that file.) The code can still be loaded into the REPL though.

Conversely flycheck does not complain about, say, use of tuple sections when `TupleSections` is not enabled. I am newish to writing Haskell in emacs (well, Spacemacs) so my apologies if I've missed something about the syntax checker's behavior.

**Comment by lunaryorn** [comment]
Hello,

Flycheck does not look at Cabal files itself.  You need to install and setup [flycheck-haskell](https://github.com/flycheck/flycheck-haskell/) for this purpose which parses the Cabal file and sets up Flycheck accordingly.

I do not know whether Spacemacs already does that; you may want to take a look at the Haskell layer.  I think that this is more an issue with Spacemacs' Haskell configuration, so please take this problem to the Spacemacs issue tracker.

Thank you.

**Comment by lunaryorn** [comment]
@t-ander Did you install this package?  I.e. `flycheck-haskell` in addition to `flycheck` itself?  You may want to take a look at the Haskell layer in Spacemacs, and make sure that it's properly enabled and all packages are present.

Please show the output of `C-c ! C-c haskell-ghc` in an affected buffer.

**Comment by t-ander** [comment]
Sorry for any confusion, the error was being reported by hlint since it deliberately enables only certain extensions by default. The variable `flycheck-hlint-language-extensions` gives me the functionality I was looking for.
