### ISSUE TITLE
stack build command should be done in project root directory

### ISSUE THREAD

**Issue by maxigit** [flycheck/flycheck-haskell#58]
At the moment, the `stack ghc` command needed to check a file is executed in the directory file instead of the project root. This breaks template haskell function using relative path (example `persistWithFile` use in Yesod scaffholding).
 The project root can be  found by running `stack path --project-root`.

**Comment by lunaryorn** [comment]
Thank you for reporting this issue.  We do not currently support this in Flycheck, but are in the process of adding it.  Please see https://github.com/flycheck/flycheck/pull/813.

Thank you.
