### ISSUE TITLE
"Suspicious state from syntax checker haskell-stack-ghc"

### ISSUE THREAD

**Issue by ocramz** [flycheck/flycheck-haskell#59]
"[..] Checker haskell-stack-ghc returned non-zero exit code 1, but no errors from output."

I'm using the latest GHC for OSX (ghc 7.10.3), Emacs 24.5.1, and the above error message appears after activating flycheck-mode.

Here are the pertinent section of my `init.el`

```
(autoload 'ghc-init "ghc" nil t)
(autoload 'ghc-debug "ghc" nil t)

(add-hook 'haskell-mode-hook (lambda () (ghc-init)))
(add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
(add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)

(eval-after-load 'flycheck
  '(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup))

(custom-set-variables
 '(exec-path
   (quote
    ("/usr/bin" "/bin" "Users/ocramz/.local/bin" "/usr/sbin" "/Applications/ghc-7.10.3.app/Contents/bin" "/sbin" "/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9" "/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9" "/Applications/Emacs.app/Contents/MacOS/libexec" "/Applications/Emacs.app/Contents/MacOS/bin")))
 '(haskell-interactive-mode-hide-multi-line-errors nil)
 '(haskell-process-log t)
 '(haskell-process-type (quote auto))
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa-stable.milkbox.net/packages/")
     ("melpa-stable" . "http://stable.melpa.org/packages/")))))
)


```

**Comment by lunaryorn** [comment]
Hello.

Thank you very much for reporting this issue.  We will try to address it as soon as possible.  However, we need additional information from you.  Please tell us

- your Flycheck version, as in `M-x flycheck-version`,
- and the output of `M-x flycheck-verify-setup` in an affected buffer.

Please also include the *complete* error message.  You can copy it from the `*Messages*` buffer.

It'd be awesome if you could try to [reproduce the bug in `emacs -Q`](http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html) as well, and provide a step-by-step recipe for us to reproduce the issue as well.

Please add a comment with all this information.  If you think that you already provided all necessary information please tell us as well.   If you have difficulties with specific steps please do not hesitate to ask.

Thank you very much for using Flycheck, and for taking the time to report this issue.  We are looking forward to work with you to solve this problem :blush:

-----

This is one of me [saved replies](https://github.com/blog/2135-saved-replies).  I am using this feature to help me reduce the time spend on triaging issues in Flycheck :relaxed:  If you feel that saved replies are not appropriate, please tell me.  Thank you.

**Comment by ocramz** [comment]
* Flycheck version 26

* ```M-x flycheck-verify-setup``` : I don't understand why, even after restarting Emacs, `flycheck` isn't found (it's in my `.local/bin`):
```
$ which hlint
/Users/ocramz/.local/bin/hlint

$ hlint --version
HLint v1.9.31, (C) Neil Mitchell 2006-2016
```

```
Syntax checkers for buffer Vec.hs in haskell-mode:

  haskell-stack-ghc
    - predicate:  t
    - executable: Found at /usr/bin/stack

  haskell-ghc
    - predicate:  t
    - executable: Found at /Applications/ghc-7.10.3.app/Contents/bin/ghc

  haskell-hlint
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.
```

*  After turning on Flycheck, the following appears:
```
Suspicious state from syntax checker haskell-stack-ghc: 
Checker haskell-stack-ghc returned non-zero exit code 1, but no errors from output: 
No compiler found, expected minor version match with ghc-7.10.3 (x86_64) 
(based on resolver setting in /Users/ocramz/Dropbox/RESEARCH/Haskell/petsc-hs/stack.yaml). 
Try running stack setup to locally install the correct GHC
Checker definition probably flawed.
```

**Comment by ocramz** [comment]
FIXED, after modifying my `~.emacs.d/init.el` as follows: 

* INSTALLING exec-path-from-shell (https://github.com/purcell/exec-path-from-shell)

* COMMENTING OUT
```
(eval-after-load 'flycheck		
   '(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup))
```

* ACTIVATING `global-flycheck-mode` (adding the entry ` '(global-flycheck-mode t)` in the list `(custom-set-variables )` in `init.el`).

Thank you @lunaryorn , also for the blog about `emacs -Q` , which taught me a few useful things.

**Comment by lunaryorn** [comment]
@ocramz You're welcome.  I'm happy to hear that you could solve this problem.  Thanks for reporting the issue.

**Comment by raghuugare** [comment]
Was about to report a similar issue here. Thank you @ocramz & @lunaryorn !
(In my case, the issue cropped up when I switched from cabal to stack & back to cabal--in any case, I wish that we all move towards 1 preferred system soon which means less headaches for everyone!)

@lunaryorn - special thanks for your blog on the `emacs -Q` option. Will definitely share it on!

Keep up the great work!

**Comment by bigos** [comment]
Since Google lists this issue at the top I thought I would add my comment. I had this error:

> Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: Run from outside a project, using implicit global project config
> Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in /home/jacek/.stack/global-project/stack.yaml).

I have edited the relevant file
`nano ~/.stack/global-project/stack.yaml `
Ang changed the resolver from resolver: lts-8.15 to:

`resolver: ghc-7.10.3`

Please comment what you think and perhaps point me to a better solution.
