### ISSUE TITLE
-fno-code does not fly with template haskell

### ISSUE THREAD

**Issue by gracjan** [flycheck/flycheck-haskell#6]
Setup:
SourceWithSomeTHDefinitions.hs
SourceUsingThoseTHDefinitions.hs

When doing flycheck over SourceUsingThoseTHDefinitions.hs it finds and imports SourceWithSomeTHDefinitions.hs properly but the bails out with:

ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  XYziDerive_newtypeDeriveReadShow_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org

Reason: SourceWithSomeTHDefinitions.o wasn't created so Template Haskell could not be loaded.

I guess running without -fno-code is problematic. But when first run fails with ByteCodeLink.lookupCE then a second run without -fno-code could be made. But that requires temporary directory setup. Overall this is not fun.

**Comment by vlatkoB** [comment]
I'm getting the same error when opening any `.hs` file in `Yesod` project. Except the missing symbol is `Settings_compileTimeAppSettings_closure`.

Can you tell me where should the @gracjan's `:command` workaround be placed?

**Comment by vlatkoB** [comment]
Found the solution.

**Comment by vlatkoB** [comment]
If I do not edit `flycheck.el` after every update and replace command for `haskell-ghc` with
`:command ("ghc" "-Wall" "-no-link" "-outputdir" "/tmp/flycheck-haskell"`
it is totally unusable, only `ByteCodeLink.lookupCE` errors. :-(

Is there a way to replace/override just the `haskell-ghc` checker? Something like `advice-add` maybe?

@lunaryorn Or would you agree to add a `haskell-ghc-custom-options` var so the user can specify the arguments?
Something like
```elisp
:command ("ghc" (if (boundp haskell-ghc-custom-options)
                     (haskell-ghc-custom-options)
                    ("-Wall" "-fno-code")) ....
```

And user can:
`(setq haskell-ghc-custom-options '("-Wall" "-no-link" "-outputdir" "/tmp/flycheck-haskell"))`

**Comment by lunaryorn** [comment]
@vlatkoB You can simply redefine the checker.  I'll not accept any such variable, but I see the issue, and I'd accept a PR that changes the Haskell GHC syntax checker to write its output to a cache directory.

**Comment by vlatkoB** [comment]
Thanks for the redefining tip. I thought it has to be advised like funcs.

Did you mean something like this?
```elisp
:command ("ghc" "-Wall" "-no-link" 
            "-outputdir" (eval (expand-file-name ".cache/flycheck-haskell" "~"))
```

**Comment by lunaryorn** [comment]
@vlatkoB Yes, something similar, but in an proper temporary directory.  There are already syntax checkers in Flycheck that do something similar…  iirc, SASS for instance.

**Comment by vlatkoB** [comment]
So, something like
```elisp
(defvar flycheck-haskell-ghc-cache-directory nil)

(defun flycheck-haskell-ghc-cache-location ()
  (setq flycheck-haskell-ghc-cache-directory
        (or flycheck-haskell-ghc-cache-directory
            (make-temp-file "flycheck-haskell-ghc-cache" 'directory))))

(flycheck-define-checker haskell-ghc
  :command ("ghc" "-Wall" "-no-link" 
            "-outputdir" (eval (flycheck-haskell-ghc-cache-location))
...
```

**Comment by lunaryorn** [comment]
@vlatkoB Yes.

**Comment by vlatkoB** [comment]
[Done](https://github.com/flycheck/flycheck/pull/708).
