### ISSUE TITLE
Support GHC8 Error Messages

### ISSUE THREAD

**Issue by creichert** [flycheck/flycheck-haskell#62]
I've been using the `haskell-stack-ghc` checker since it was released and I haven't had a single issue. However, GHC 8 seems to have a slightly different error message structure which keeps the error messages from properly showing in the minibuffer.

![img4](https://cloud.githubusercontent.com/assets/526560/15809345/af6cabda-2b54-11e6-9e71-0dd5d3354f93.jpg)

If I run `M-x flycheck-compile RET haskell-stack-ghc` manually, the error message looks like this:

```
/home/me/dev/haskell/keter/Data/Yaml/FilePath.hs:65:29: error:
    Not in scope: type constructor or class ‘PareYamlFile’
    Perhaps you meant ‘ParseYamlFile’ (line 53)

```

--

if you need a `stack.yaml` file to reproduce:

```
flags:
  keter: {}
packages:
- '.'
extra-deps: []
resolver: nightly-2016-06-02
```

There are a few other interesting changes to the error messages, I'll post them if they are useful.

**Comment by lunaryorn** [comment]
@creichert Did you update Flycheck today?  I think the issue [has already been fixed](https://github.com/flycheck/flycheck/pull/982).

**Comment by creichert** [comment]
Great, I didn't check that repo but just updated and everything is working again. Thanks!
