### ISSUE TITLE
Switching GHC versions

### ISSUE THREAD

**Issue by ocramz** [flycheck/flycheck-haskell#63]
If there are more than one Haskell installations present (e.g. I have 7.8.4, 7.10.3 and 8.0.1), is there a compact way of pointing flycheck-haskell at the desired one? 

I'm encountering this "suspicious state from syntax checker haskell-stack-ghc" warning, since the checker is stuck at using 7.10, whereas I need to try something with 7.8 . 

It's a single .hs file, there is no cabal or stack.yaml file, so the default "Try running stack setup to locally install the correct ghc" is misleading.

Thank you

**Comment by lunaryorn** [comment]
As far as I know you can switch GHC versions in stack without changing the resolver which is not possible in Flycheck currently.

But you can just switch to the normal GHC syntax checker and point its executable to the desired GHC version.

**Comment by ocramz** [comment]
And how is this done? I'd like to change the path that's displayed when calling `M-x flycheck-verify-setup`, under `haskell-ghc`. I forgot how to access the menu that lets me modify that path variable. Thank you

**Comment by lunaryorn** [comment]
@ocramz You can `C-c ! s` to select a specific syntax checker, or `C-c ! x` to disable the undesired ones, and then use `C-c ! e` to select the executable of the GHC syntax checker.

**Comment by ocramz** [comment]
@lunaryorn there seems to be a configuration wrapper around `hlint`. Does `C-c ! e` have to point at this file, or at `hlint`?

**Comment by lunaryorn** [comment]
I'm sorry but I don't understand your question.  I thought  we were talking about GHC?

**Comment by ocramz** [comment]
Just an aside re. your comment on syntax checkers. I've solved the issue by `M-x customize-variable`ing `exec-path`. Thank you
