### ISSUE TITLE
"Checker definition prob. flawed" after switching Stackage resolver

### ISSUE THREAD

**Issue by ocramz** [flycheck/flycheck-haskell#64]
Flycheck 28, Emacs 24.5.1 x86_64-apple-darwin13.4.0

1. change Stackage resolver (in my case, from `lts-5.15` (GHC 7.10.3) to `nightly-2016-06-20` (GHC 8.0.1)), retrigger Flycheck

2. Flycheck turns off with the following error message :  
```
Checker definition probably flawed.
Suspicious state from syntax checker haskell-stack-ghc: Checker haskell-stack-ghc returned non-zero 
exit code 1, but no errors from output: After installing Cabal, the package id couldn't be found 
(via ghc-pkg describe Cabal). This shouldn't happen, please report as a bug
```
4. `stack install hlint` (even though it was already in `$HOME/.local/bin` and working just fine under GHC 7.10.3) (I thought the bug was due to `hlint` being compiled for/by the wrong GHC version)

5. Same error message

Thanks in advance for all pointers

**Comment by ocramz** [comment]
Interestingly, when I revert Stackage resolver in my `stack.yaml`, Flycheck switches on again

**Comment by lunaryorn** [comment]
@ocramz I don't know what's going on, but to me that looks like a Stack issue.  At least, we're not doing anything unusual with Stack.

**Comment by ocramz** [comment]
@lunaryorn Does it rely on the `ghc-pkg` that's returned by `which`, or on the first one that it can retrieve in the Emacs `exec-path`? In my case they point to distinct Haskell versions. The first entry in the `exec-path` is the one I want to use (GHC 8.0.1), so I wonder what's the matter. This error message only occurs on projects that have a `stack.yaml` file.  Thanks again

**Comment by lunaryorn** [comment]
@ocramz Sorry, but I can't follow your comment.

>  Does it rely on the ghc-pkg that's returned by which, or on the first one that it can retrieve in the Emacs exec-path?

Sorry, but what are you asking? What do you mean with `which`?

I should point out that Flycheck doesn't use `ghc-pkg` at all.  The error messages comes from `stack` not Flycheck.

**Comment by ocramz** [comment]
`which` is a Unix command that returns the path of a systems binary. I'm asking where does Flycheck look for binaries, whether via issuing the `which` command or by looking them up via the list of paths in `exec-path`
. 
The error message mentions `ghc-pkg`, which is why I started wondering about mismatching versions of it. Does the latest version of `flycheck-haskell` have specific GHC version requirements?

**Comment by lunaryorn** [comment]
@ocramz Being an Emacs extension Flycheck looks at `exec-path`, of course.  But I'm not sure how that's relevant here.  

Again, this error message doesn't come from Flycheck or Flycheck Haskell.  It's directly from `stack ghc`… so I'm not sure why it matters how Flycheck searches for binaries.

**Comment by ocramz** [comment]
@lunaryorn Ok, thanks anyway. I'll keep looking for errors elsewhere.
