### ISSUE TITLE
Support new cabal builds

### ISSUE THREAD

**Issue by slpopejoy** [flycheck/flycheck-haskell#65]
Cabal new-build uses a new dist dir layout, and requires `package-db` locations in the ghc call. I got it to work with the following changes:

`get-cabal-configuration.hs`: see commit on my fork https://github.com/flycheck/flycheck-haskell/commit/d1a7cd817003ecaf19466b940b6277b0725a110f . 

Added package-dbs using .dir-locals for my project. I'm on ghc 8.0.1, and the project is `fadno`, with the dist dir being `dist-newstyle/build/fadno-1.0.0`:

```
(flycheck-ghc-package-databases "/Users/stuart/.cabal/store/ghc-8.0.1/package.db" "/Users/stuart/dev/fadno/dist-newstyle/packagedb/ghc-8.0.1" "/Users/stuart/dev/fadno/dist-newstyle/build/fadno-1.0.0/package.conf.inplace")
```

Might be nice to get input from @ezyang (or other new-cabal wizards) as to how to do this properly, and how stable this stuff is. For instance, the `dist-newstyle` stuff is available in cabal-install: https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/DistDirLayout.hs#L110 

But not in Cabal library, so not accessible (?) in get-cabal-configuration.hs. DistDirLayout seems to show that this path can be more complex than simply dist-newstyle/build/foo-version/build etc, so not sure how hacky my solution is thus far.

But it does seem that we would want to discover the package-db invocations.

**Comment by lunaryorn** [comment]
@slpopejoy I'm normally using stack and am not following Haskell development closely, so I'd appreciate a bit of background information.  I've got no idea what "Cabal new-build" is, how it's different, and why and how that affects flycheck-haskell, and I'm not sure what you're referring to with "we would want to discover the package-db invocations.".

/cc @flycheck/haskell

**Comment by slpopejoy** [comment]
Cabal new-build is great new work on cabal that eliminates the need for sandboxes in most cases, effortlessly handles different GHC versions, doesn't require dedicated `cabal configure` etc etc. There's a ton of work under the hood going on. See http://blog.ezyang.com/2016/05/announcing-cabal-new-build-nix-style-local-builds/ for an intro. 

My backstory: I recently upgraded some libraries on hackage, and the docs failed to build b/c hackage uses GHC 8x for doc build. I asked on \#haskell-infrastructure what was the best way forward -- I was dreading having two cabal sandboxes for 8x and 7.10.x -- and they pointed me at new-build. I'm happy to say the hype is real :) and it all works beautifully, I had my libs compiling with both GHCs very quickly. 

Anyway, all was well except for emacs :) . I haven't found any indication of work being done on this in haskell-mode or flycheck, maybe I've missed something. I was able to get things working in both, however, so I thought I'd open issues to document what I've done and start a discussion how to best support these. Sorry for the mess!

Apparently, soon new-build will be the preferred way to use cabal (I'm certainly not going back, also see https://github.com/haskell/cabal/issues/3852) so one discussion item is whether emacs tools can simply cut over, or at what point etc. Clearly, not having to support both would make things considerably simpler.

Specifics thus far:
1. The change to `get-cabal-configuration.hs` works, but might need to provide more info (ie package-db stuff).
2. As indicated above, I had to get the checker to add three `-package-db` entries to the command line, which I did via customization for now. This might be something `get-cabal-configuration.hs` should do.
3. None of this info is in Cabal-the-library yet, would be nice to get info from the source clearly.

**Comment by lunaryorn** [comment]
That sounds very promising, for sure, and I'm all for burning bridges and move to the new style Cabal support without any concerns for backwards compatibility, but I'm not yet sure whether I see a clear path forward.

For one, it seems that "new build" itself still seems to be a bit unstable—why wouldn't it be the default otherwise.  And then I'd love to see the new-build behaviour being exposed through Cabal-the-library, for directly accessing the .store package DB in ~/.cabal feels, well, hacky.  Ideally we'd have any API that allows to get a list of all package databases required for compilation.

That didn't exist for sandboxes, which was not too nice, but sandboxes are somewhat simple, whereas new-build seems to be more involved, which would open up for subtle differences between the ways flycheck checks and cabal builds unless we're really sure to check the same, i.e. because we get all the information through the API.

**Comment by slpopejoy** [comment]
Agreed on all points. I'm happy to maintain a fork or something as this develops.

**Comment by mrkkrp** [comment]
Nothing new here?

**Comment by sergv** [comment]
As before, it seems very desirable to have some kind of API exposed by `Cabal` package that would return all packge dbs necessary for compiling current project. Are aware of such thing being exposed?

**Comment by Rizary** [comment]
`cabal new-build` will soon become `build` 

reference: https://github.com/haskell/cabal/projects/6

**Comment by sergv** [comment]
Yeah, we should probably do something about that. Not sure that I've got spare resources to implement that any time soon. PR for that would be terrific, though.

On 5 August 2018 15:56:00 BST, Andika Demas Riyandi <notifications@github.com> wrote:
>`cabal new-build` will soon become `build` 
>
>reference: https://github.com/haskell/cabal/projects/6
>
>-- 
>You are receiving this because you are on a team that was mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/flycheck/flycheck-haskell/issues/65#issuecomment-410525591

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
