### ISSUE TITLE
Support hpack files directly

### ISSUE THREAD

**Issue by jbaum98** [flycheck/flycheck-haskell#85]
It would be nice if rather than having to generate a new cabal file every time the hpack file was edited, we could run hpack on the file ourselves and parse the output of that. Then it would be cached the same, so there wouldn't be much overhead after unless the cache was cleared.

This would require modify the helper haskell program to accept the cabal file on stdin, and then somehow specifying the information it gets from the file name via a command line arg.

**Comment by sergv** [comment]
Which package description format should be the default one? If both `.cabal` and `package.yaml` files are present, should `flycheck-haskell` at all look at `package.yaml`? Or should it reach for `package.yaml` only if cabal file is absent?

**Comment by jbaum98** [comment]
I think there should be a variable to decide the precedence, but if you have both a package.yaml.and a cabal file it seems to me like the cabal file was probably generated from the package.yaml and not the other way around, so we should give the hpack file precedence.

**Comment by jbaum98** [comment]
Added in #86.
