### ISSUE TITLE
Support for cabal.project?

### ISSUE THREAD

**Issue by jwiegley** [flycheck/flycheck-haskell#97]
I have a group of projects included a by `cabal.project` file. Say for the sake of example that there are two, `foo` and `bar`, where `bar.cabal` has a `build-depends` reference to `foo`.

I use `cabal new-build all` to build both `foo` and `bar`. When I go to edit a file in `bar`, flycheck-haskell says that it can't satisfy the dependency for `foo`, because sure enough it's not in the output from `ghc-pkg list`, for example.

Is there any way to teach flycheck-haskell to look at the other projects built within the `cabal.project` project?

**Comment by sergv** [comment]
Hi, sorry for late reply. There's no way to make `flycheck-haskell` look inside `cabal.project` at the moment. As I'm using stack integration for the time being the only way to get that is via PR from someone who does use `flycheck-haskel` with `cabal new-build`.
