### ISSUE TITLE
Reference to Distribution.Parsec.Common needs to be updated for Cabal-3.0.0.0

### ISSUE THREAD

**Issue by skalyan91** [flycheck/flycheck-haskell#99]
When I try to load a Haskell file in Emacs, I get an error about `get-cabal-configuration.hs` not being able to load `Distribution.Parsec.Common`. And indeed, `Distribution.Parsec.Common` does not exist on Hackage. This seems to be caused by the fact that `flycheck-haskell` hasn’t been updated for Cabal-3.0.0.0 (which just came out last month).

Would appreciate a fix, or at least a temporary workaround.

**Comment by sergv** [comment]
Thanks for reporting. Should be fixed now. If not, please shout.
